site_name: Surgical robotics challenge
site_dir: docs

# Needed to avoid changes in the relative paths
# https://stackoverflow.com/questions/48063231/mkdocs-hyperlink-not-working-in-static-pages
use_directory_urls: false

theme:
  name: spacelab
  highlightjs: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Python API:
      - overview: python_api/python_package_overview.md
      - API reference: python_api/python_api.md
  - Tutorials:
      - Overview: "./Tutorials/README.md"
      - 1. Camera Conventions: "./Tutorials/camera_conventions.md"
      - 2. Coordinate frames: "./Tutorials/scene_coordinate_frames.md"
      - 3. Teleoperation: "./Tutorials/teleoperation_devices.md"

copyright: LCSR, Johns Hopkins University.

## Other configs
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - toc:
      permalink: "#"

plugins:
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: numpy
