site_name: Surgical robotics challenge
site_dir: docs
use_directory_urls: false

theme:
  name: slate
  highlightjs: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API: api.md
  - Tutorials: Tutorials/

copyright: LCSR, Johns Hopkins University.

## Other configs
markdown_extensions:
  - markdown_include.include:
      base_path: .
